# In addition to the standard set of inclusions, include `.pyw` files.
extend-include = ["*.pyw"]

# Allow autofix
fix = true

# Allow lines to be as long as 120.
line-length = 120

# Enumerate all fixed violations.
show-fixes = true

unsafe-fixes = true


[format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true

[lint]
# Relaxed ruleset
select = [
    "A",   # Shadowing Python builtin
    "E4",  # Module imports
    "E7",  # Some important gotchas
    "E9",  # I/O and syntax errors
    "F",   # Some important gotchas
    "PIE", # Some important gotchas
]

# Skip annoying rules
ignore = [
    "E501", # Line too long
    "E722", # Do not use bare `except`
    "E731", # Do not assign a `lambda` expression, use a `def`
    "E74",  # Ambiguous variable, class, and function names
    "F403", # Unable to detect undefined names from star imports
    "F405", # May be undefined, or defined from star imports
    "F841", # Unused variable
]

task-tags = ["TODO", "FIXME", "XXX", "HACK"]
